import { z } from 'zod';
import { type InferSchema } from 'xmcp';
import prisma from '@/lib/data/db';
import { getPairingInfo } from '@/lib/data/mcp-authorization';
import { isUserErrorResponse } from '@/lib/user-error';

import jwt from 'jsonwebtoken';
import { env } from '@/lib/ms-config/env-vars';

// Define the schema for tool parameters
export const schema = {
  code: z.string().describe('The access code generated by the user.'),
};

// Define tool metadata
export const metadata = {
  name: 'get-access',
  description:
    'Get a JWT that grants access to the other API tools. To check that the user can generate the JWT they have to provide a code generated through the MS UI.',
  annotations: {
    title: 'Get Access',
    readOnlyHint: false,
    destructiveHint: true,
    idempotentHint: false,
  },
};

// Tool implementation
export default async function getAccess({ code }: InferSchema<typeof schema>) {
  const pairingInfo = await getPairingInfo(code);

  if (isUserErrorResponse(pairingInfo)) return 'Error: Some other error'; //return `Error: ${pairingInfo.error.message}`;

  const secret = env.IAM_MCP_ACCESS_ENCRYPTION_SECRET;

  if (!secret) {
    console.error(
      'The mcp pairing endpoint was accessed but there is no encryption secret. Please set IAM_GUEST_CONVERSION_REFERENCE_SECRET in the environment if you want to use MCP.',
    );

    return 'Error: MCP not enabled';
  }

  const payload = {
    // TODO: check what the user can do and limit the scope
    environmentId: pairingInfo.environmentId,
    scope: ['processes:read'],
  };

  const ttl = 15 * 60;

  const token = jwt.sign(payload, secret, {
    issuer: 'PROCEED MS',
    audience: 'mcp',
    subject: pairingInfo.userId,
    expiresIn: `${ttl}s`,
  });

  return token;
}
