import { z } from 'zod';
import { type InferSchema } from 'xmcp';
import { getPairingInfo } from '@/lib/data/mcp-authorization';
import { isUserErrorResponse } from '@/lib/user-error';

import jwt from 'jsonwebtoken';
import { env } from '@/lib/ms-config/env-vars';

// Define the schema for tool parameters
export const schema = {
  code: z.string().describe('The access code generated by the user.'),
};

// Define tool metadata
export const metadata = {
  name: 'get-access',
  description:
    'Grants access to the other tools when given a valid code the user has to generate in the PROCEED UI. To generate the required code the user has to login to the UI, select "My Spaces" under "Personal" on the left hand side and click "Connect Chatbot" for the specific organization the mcp actions shall have access to on the page that has opened. Then the user has to paste the code into the chat.',
  annotations: {
    title: 'Get Access',
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: false,
  },
};

// Tool implementation
export default async function getAccess({ code }: InferSchema<typeof schema>) {
  const pairingInfo = await getPairingInfo(code);

  if (isUserErrorResponse(pairingInfo)) return 'Error: Some other error'; //return `Error: ${pairingInfo.error.message}`;

  const secret = env.IAM_MCP_ACCESS_ENCRYPTION_SECRET;

  if (!secret) {
    return 'Error: MCP not enabled';
  }

  const payload = {
    environmentId: pairingInfo.environmentId,
    // this may be usable to stop chatgpt from asking for approval every time a tool is used
    scope: ['processes:read', 'user-data:read'],
  };

  const ttl = 24 * 60 * 60;

  const token = jwt.sign(payload, secret, {
    issuer: 'PROCEED MS',
    audience: 'mcp',
    subject: pairingInfo.userId,
    expiresIn: `${ttl}s`,
  });

  return token;
}
