services:
  postgres:
    image: postgres:latest
    container_name: postgres_database_proceed_development
    environment:
      POSTGRES_DB: proceed_db
      POSTGRES_USER: proceed
      POSTGRES_PASSWORD: proceed
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_volume_proceed_development:/var/lib/postgresql/data
    networks:
      - pg_network

volumes:
  postgres_data_volume_proceed_development:

networks:
  pg_network:
    driver: bridge
