# build with: docker compose -f ./docker-compose-dev-iam.yml up; start with: docker compose -f ./docker-compose-dev.yml up
# only run redis with: docker compose -f ./docker-compose-dev.yml up redis
# only run opa with: docker compose -f ./docker-compose-dev.yml up opa

version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    container_name: proceed-redis
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD:-password}
    ports:
      - 6379:6379
    volumes:
      - session_storage:/data
    networks:
      proceed:

  rules_redis:
    image: 'redis:alpine'
    container_name: proceed-redis-rules
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD:-password}
    ports:
      - 6380:6379
    volumes:
      - rules_storage:/data
    networks:
      proceed:

volumes:
  session_storage:
    name: session_storage
  rules_storage:
    name: rules_storage

networks:
  proceed:
    name: proceed
