module.exports = {
  name: 'management-system',
  displayName: 'Management System',
  setupFiles: ['./tests/unit/index.js'],
  moduleFileExtensions: ['js', 'jsx', 'json', 'vue'],
  transform: {
    '^.+\\.vue$': 'vue-jest',
    '.+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
    '^.+\\.jsx?$': 'babel-jest',
  },
  transformIgnorePatterns: ['/node_modules/(?!bpmn-js|diagram.js)', '<rootDir>/build/'],
  moduleNameMapper: {
    '^./ms-api-interface/(.*).js$': '<rootDir>/src/frontend/backend-api/ms-api-electron/$1.js',
    '^(.*)/dirname-node.js$': '$1/dirname-webpack.js',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^electron$': '<rootDir>/tests/mocks/electron.js',
    '^bpmn-moddle$': '<rootDir>/tests/mocks/bpmn-moddle.js',
    'DataInterface.js$': '<rootDir>/tests/mocks/DataInterface.js',
    'ProcessInterface.js$': '<rootDir>/tests/mocks/ProcessInterface.js',
    'EngineInterface.js$': '<rootDir>/tests/mocks/EngineInterface.js',
    'backend/shared-electron-server/engine/index.js$': '<rootDir>/tests/mocks/engine.js',
    'opa-client.js$': '<rootDir>/tests/mocks/opa-client.js',
    'fs-extra': '<rootDir>/tests/mocks/fs-extra.js',
  },
  snapshotSerializers: ['jest-serializer-vue'],
  testMatch: ['**/tests/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx)'],
  testPathIgnorePatterns: ['<rootDir>/build/', '/node_modules/'],
  testURL: 'http://localhost/',
  watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
};
