on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: 'yarn'

      - run: yarn install --frozen-lockfile --ignore-engines

      - uses: actions/cache@v4
        timeout-minutes: 2
        id: cache-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: install
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      issues: write
    environment: Staging
    env:
      MS_TAG: edge
      SERVICE_NAME: ${{ inputs.environment == 'Production' && 'ms-server-production' || 'ms-server-staging' }}
      SUBDOMAIN: ${{ inputs.environment == 'Production' && 'app' || 'staging' }}
      ENV: Staging
    steps:
      - uses: 'google-github-actions/auth@v2'
        with:
          export_environment_variables: true # Exports the service account key as GOOGLE_APPLICATION_CREDENTIALS, we need this for cloud sql auth proxy
          project_id: 'proceed-bpms'
          workload_identity_provider: 'projects/1062024918148/locations/global/workloadIdentityPools/github-ci/providers/github'
          service_account: 'github-actions@proceed-bpms.iam.gserviceaccount.com'

      - name: Configure Cloud SQL Auth Proxy Docker
        run: |
          cat $GOOGLE_APPLICATION_CREDENTIALS > /tmp/key.json
          mkdir -p "$HOME/cloudsql"
          chmod 777 "$HOME/cloudsql"
          docker run -d --name cloud-sql-auth-proxy -p 127.0.0.1:3306:3306 -v /tmp/key.json:/tmp/key.json --user "$(id -u):$(id -g)" gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.3 --address 0.0.0.0 --port 3306 --credentials-file /tmp/key.json ${{secrets.INSTANCE_CONNECTION_NAME}}

          echo "DATABASE_URL=postgresql://${{ secrets.CLOUD_SQL_DB_USER }}:${{secrets.CLOUD_SQL_DB_PASS}}@127.0.0.1:3306/${{ secrets.CLOUD_SQL_DB_NAME }}" >> $GITHUB_ENV

      - name: Restore Cache
        uses: actions/cache@v4
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Apply Prisma Migrations
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          yarn dev-ms-db-deploy

      - name: deploy cloud run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          image: 'docker.io/proceed/ms-server:${{ env.MS_TAG }}'
          flags: '--add-cloudsql-instances=${{secrets.INSTANCE_CONNECTION_NAME}}'
          env_vars: |
            NEXTAUTH_URL=https://${{ env.SUBDOMAIN }}.proceed-labs.org
            DATABASE_URL=postgresql://${{ secrets.CLOUD_SQL_DB_USER }}:${{secrets.CLOUD_SQL_DB_PASS}}@localhost/${{ secrets.CLOUD_SQL_DB_NAME }}?host=/cloudsql/${{secrets.INSTANCE_CONNECTION_NAME}}/
            PROCEED_PUBLIC_DEPLOYMENT_ENV=local
          region: 'europe-west1'
          revision_traffic: LATEST=100
